### ISSUE TITLE
The ability to display the expiration date for products

### ISSUE THREAD

**Issue by jessiearellano** [jessiearellano/StarbucksIMS#5]

**Comment by briantopping** [comment]
If you want to handle expiration dates, how do you know which items were pulled from storage to go to display? If there are 10 turkey sandwiches in storage and 4 have an expiration date that is newer than the other six, we always want to pull the older sandwiches first. 
* Can the system assume if someone pulls 4 sandwiches for display that the oldest sandwiches are pulled first?
* What happens if someone accidentally pulls three older sandwiches and one newer one? Does the system now need a way to correct this?

Maybe these things don't matter for a project of this size, but then I'd ask if having expiration dates at all matters at this stage either.

**Comment by jessiearellano** [comment]
No longer going to implement expiration system. Tedious work to put in expiring dates for items consistently sold/thrown away
